
import { analyzeMood } from "@shared/mood-mapping";

const QUESTIONS = {
    opening: [
        "How was your day today?",
        "Tell me about what happened today?",
        "What was the most significant part of your day?"
    ],
    emotion: [
        "How did that make you feel?",
        "What emotions did you experience?",
        "Describe your mood in a few words."
    ],
    reasoning: [
        "Why do you think you felt that way?",
        "What triggered those feelings?",
        "Is there a deeper reason for this?"
    ],
    highlight: [
        "What was the best moment of your day?",
        "What are you grateful for today?",
        "What's one thing you want to remember from today?"
    ],
    closing: [
        "Thanks for sharing. I've saved your entry.",
        "Reflecting is powerful. I've logged this for you.",
        "Good job taking time for yourself. Entry saved."
    ]
};

function getRandomQuestion(category: keyof typeof QUESTIONS): string {
    const options = QUESTIONS[category];
    return options[Math.floor(Math.random() * options.length)];
}

export async function processJournalEntry(message: string, history: { role: "user" | "model", parts: string }[]): Promise<{ response: string, entry?: { content: string, mood: string, summary: string } }> {
    // History structure from client includes the model's greeting but NOT the current user message.
    // We can determine the "turn" based on history length.
    // History: [Model(Greeting)] -> Length 1 -> User just replied to greeting (Turn 1)
    // History: [Model, User, Model] -> Length 3 -> User just replied to Q1 (Turn 2)
    // History: [Model, User, Model, User, Model] -> Length 5 -> User just replied to Q2 (Turn 3)
    // History: [Model, User, Model, User, Model, User, Model] -> Length 7 -> User just replied to Q3 (Turn 4)

    const historyLength = history.length;

    if (historyLength <= 1) {
        // User just answered the greeting (or started). Ideally greeting was "Ready to reflect?".
        // We treat this as them starting.
        // Actually, usually greeting is "Hi...". User says "Yes".
        // Let's ask the Opening question.
        return { response: getRandomQuestion("opening") };
    } else if (historyLength <= 3) {
        // User answered Opening. Ask Emotion.
        return { response: getRandomQuestion("emotion") };
    } else if (historyLength <= 5) {
        // User answered Emotion. Ask Reasoning.
        return { response: getRandomQuestion("reasoning") };
    } else if (historyLength <= 7) {
        // User answered Reasoning. Ask Highlight.
        return { response: getRandomQuestion("highlight") };
    } else {
        // User answered Highlight. Time to wrap up.
        // We need to construct the entry from the history + current message.

        // Extract answers:
        // User msg 1 (Index 1 in full history if we had it, but here it's in `history[1]`)
        // Wait, history is: [M0, U1, M1, U2, M2, U3, M3] (Length 7)
        // Current message is U4.

        const answerDay = history[1]?.parts || ""; // Response to Greeting? Wait.
        // Let's look at the flow in Client: startNewEntry -> Messages = [{role: model, text: Greeting}]
        // User sends Msg1. API call with history=[Greeting].
        // Server sees length 1. Returns Opening Q (M1).

        // User sends Msg2. API call with history=[Greeting, Msg1, OpeningQ].
        // Server sees length 3. Returns Emotion Q (M2).

        // User sends Msg3. API call with history=[Greeting, Msg1, OpeningQ, Msg2, EmotionQ].
        // Server sees length 5. Returns Reasoning Q (M3).

        // User sends Msg4. API call with history=[Greeting, Msg1, OpeningQ, Msg2, EmotionQ, Msg3, ReasoningQ].
        // Server sees length 7. Returns Highlight Q (M4).

        // User sends Msg5. API call with history=[Greeting, Msg1, OpeningQ, Msg2, EmotionQ, Msg3, ReasoningQ, Msg4, HighlightQ].
        // Server sees length 9.

        // WE ARE HERE.

        const openingAnswer = history[3]?.parts || ""; // Response to OpeningQ
        const emotionAnswer = history[5]?.parts || ""; // Response to EmotionQ
        const reasoningAnswer = history[7]?.parts || ""; // Response to ReasoningQ
        const highlightAnswer = message; // Current message

        // Construct Content
        const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

        const content = `
# 📅 ${today}

## 🌟 Daily Overview
${openingAnswer}

## 💭 Emotional Insight
**How I felt:** ${emotionAnswer}

**Why:** ${reasoningAnswer}

## ✨ Highlight of the Day
${highlightAnswer}

---
*Generated by MoodMirror Journal Assistant*
        `.trim();

        // Analyze Mood locally based on the emotion answer
        const moodAnalysis = analyzeMood("self", emotionAnswer);
        const mood = moodAnalysis.mood;

        // Create Summary
        const summary = `Reflection on ${new Date().toLocaleDateString()}`;

        return {
            response: getRandomQuestion("closing"),
            entry: {
                content,
                mood,
                summary
            }
        };
    }
}
